import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "@/lib/Providers/ThemeProvider";
import MainNav from "@/components/MainNav";
import CustomSideBar from "@/components/CustomSidebar";
import { Toaster } from "@/components/ui/toaster";
import "simplebar-react/dist/simplebar.min.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ThemeProvider attribute="class" defaultTheme="system" enableSystem>
          <MainNav />
          <main className="grid grid-cols-5 h-[calc(100vh-4.1rem)]">
            <CustomSideBar />
            <section className="col-span-4 px-4 py-4">{children}</section>
          </main>
        </ThemeProvider>
        <Toaster />
      </body>
    </html>
  );
}
