version: '3.8'

services:
  backend:
    user: vscode
    volumes:
      - ..:/workspace:cached
    working_dir: /workspace
    command: sleep infinity

  frontend:
    user: vscode
    volumes:
      - ..:/workspace:cached
    working_dir: /workspace
    command: sleep infinity